[최창환] Mission 3 : westagram project sign_up
wecode-bootcamp-korea/31-westagram-backend-4-team pull request #6
Opened 2022-03-18 06:52 UTC by clhy9727

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- sign_up 기능 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- re모듈과 ValidationError를 사용하여 validations.py에 email, password 유효성 검사하는 클래스 생성
- validations.py의 클래스를 상속받아 views.py에서 사용
- email 중복성 검사하는 기능 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-18 07:01 UTC, bigfanoftim requested changes

2022-03-18 07:01 UTC, bigfanoftim commented on students/changhwan/users/validations.py
> +            raise ValidationError('message : Incorrect Email format')
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
import re

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(email):
    if not re.match(REGEX_EMAIL, email):
```

2022-03-18 07:01 UTC, bigfanoftim commented on students/changhwan/users/views.py
> +# from django.shortcuts import render
불필요한 주석 다 지워주세요!

2022-03-18 07:01 UTC, bigfanoftim commented on students/changhwan/users/views.py
> +            user = User.objects.create(
반환된 객체를 `user` 변수에 할당하신 이유가 따로 있나요?

2022-03-18 07:29 UTC, clhy9727 commented
피드백 해주신 부분 모두 반영했습니다.
생각해보니 굳이 user변수에 할당할 이유가 없어서 지웠습니다!

2022-03-21 05:55 UTC, bigfanoftim requested changes

2022-03-21 05:55 UTC, bigfanoftim commented on students/changhwan/users/validations.py
> +            raise ValidationError('message : Incorrect Email format')
```suggestion
            raise ValidationError('INVALID_EMAIL')
```

2022-03-21 06:34 UTC, clhy9727 commented
피드백 해주신 부분 모두 반영하여 수정했습니다.

2022-03-21 06:38 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-21 06:48 UTC, merged