[이원빈] Mission4 : 로그인 기능 구현
wecode-bootcamp-korea/31-westagram-backend-4-team pull request #7
Opened 2022-03-21 06:53 UTC by Onbin97

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-로그인 기능 구현
-validator를 활용하여 이메일과 비밀번호가 맞는지 확인하기전에 각 양식에 맞는지 부터 확인

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 07:08 UTC, clhy9727 reviewed
고생하셨습니다! 원빈님
멘토리뷰 ㄱㄱ!

2022-03-22 01:21 UTC, kyeongraekim requested changes

2022-03-22 01:21 UTC, kyeongraekim commented on students/wonbin/users/views.py
> +        except ObjectDoesNotExist:
ObjectDoesNotExist외에 Model.DoesNotExist 라는 예외문이 따로 있습니다. 둘의 역할과 기능을 비교해보시고 어느 것을 사용하는 것이 더 좋은지 한 번 고민해주세요!~

2022-03-22 01:21 UTC, kyeongraekim commented on students/wonbin/users/views.py
> +            if not User.objects.get(email = email).password == password:
"if not" vs "!=" 
위 두개념에 대해서 차이점을 혹시 고민해 보셨을까요? 어떠한 차이가 있는지 한 번 리서치를 해보고 어느 방향을 선택할지 한 번 고민해보세요!~

2022-03-22 02:10 UTC, Onbin97 commented on students/wonbin/users/views.py
> +        except ObjectDoesNotExist:
원하는 class의 에러처리를 더 명확히 할 수 있어서 Model.DoesNotExist 가 사용하기 좋을 것 같습니다.

2022-03-22 02:12 UTC, Onbin97 commented on students/wonbin/users/views.py
> +            if not User.objects.get(email = email).password == password:
if not은 뒤에 비교하는대상이 명확히 있을때는 오히려 두번 구문을 돌리기 때문에, 비효율적인것 같습니다. 그래서 if 뒤에 비교하는 값이 없고 boolen값을 확인할때 써야합니다.

2022-03-22 06:03 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 06:04 UTC, merged