[최창환] Mission 4 : westagram project sign_in
wecode-bootcamp-korea/31-westagram-backend-4-team pull request #8
Opened 2022-03-21 07:33 UTC by clhy9727

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 계정을 잘 못 입력한 경우 {"message": "INVALID_USER"}, status code 401 return
- 비밀번호를 잘 못 입력한 경우 {"message": "INVALID_PASSWORD"}, status code 401 return
- 로그인 성공 시 {"message": "SUCCESS"}, status code 200 return

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 07:46 UTC, Onbin97 commented
창환님! 저 코드로 가동하면 불러온 이메일에서 패스워드를 입력할때, 데이터베이스에 저장되어 있는 다른 사람의 비밀번호를 입력해도 로그인이 될 것 같은데 한번만 확인 부탁드려요. 그 이메일에 해당하는 사람의 비밀번호랑 일치하는지 확인이 안될것 같아요!

2022-03-21 08:00 UTC, clhy9727 commented
매칭되는 email password만 로그인이 되도록 수정했습니다.

2022-03-22 01:27 UTC, kyeongraekim requested changes

2022-03-22 01:27 UTC, kyeongraekim commented on students/changhwan/users/views.py
> +                return JsonResponse({"message":"INVALID_PASSWORD"}, status=401)
해당 내용은 굳이 따로 변수처리를해서 빼지 않는게 더 효율적으로 보일 것 같네요!~

그리고 비밀번호에 대한 내용도 invalid_user 로 통일해주셔서 어떠한 부분에서 난 오류인지 클라이언트가 메세지를 받았을 때 명확하게 알 수 없게 (보안성 강화를 위해) 수정해주세요~

2022-03-22 03:59 UTC, clhy9727 commented
피드백 해주신 부분 반영하여 수정하였습니다!

2022-03-22 07:01 UTC, bigfanoftim requested changes

2022-03-22 07:01 UTC, bigfanoftim commented on students/changhwan/users/views.py
> +            if not User.objects.get(email=email).password == password:
`filter`, `exists` 메소드를 이용하여 INPUT으로 받은 `email`과 `password`를 동시에 만족하는 `User`를 조회 하도록 코드를 작성하면 가독성이 더 좋아질 것 같습니다.

```python
def post(self, request):
    data = json.loads(request.body)

    if not User.objects.filter(email = data["email"], password = data["password"]).exists():
        return JsonResponse({'message' : 'INVALID_USER'}, status=401)

    return JsonResponse({'message' : 'LOGIN SUCCESS'}, status=200)
```

2022-03-22 07:14 UTC, clhy9727 commented
피드백 해주신 부분 반영하여 수정하였습니다!

2022-03-22 07:21 UTC, bigfanoftim requested changes

2022-03-22 07:21 UTC, bigfanoftim commented on students/changhwan/users/views.py
> +            return JsonResponse({'message':'KeyError'}, status=400)
에러 메세지같은 경우 모든 메시지를 같은 양식으로 작성해주세요.
```python
# BAD
...
return JsonReponse({'message' : 'key error'}, ...)
...
return JsonReponse({'message' : 'FAIL'}, ...)
...
return JsonReponse({'message' : 'invalid_user'}, ...)

# GOOD
...
return JsonReponse({'message' : 'KEY_ERROR'}, ...)
...
return JsonReponse({'message' : 'SUCCESS'}, ...)
...
return JsonReponse({'message' : 'INVALID_USER'}, ...)
```

2022-03-22 07:29 UTC, clhy9727 commented
피드백 해주신대로 views.py의 에러메시지를 모두 수정했습니다.

2022-03-22 07:31 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 07:31 UTC, merged